config/routes.rb
Rails.application.routes.draw do
  resources :machine_in_sections
  resources :sections
  resources :machines
  resources :component_in_machines
  resources :component_materials
  resources :components
  resources :buy_options
  resources :materials
  resources :people
  resources :planets
  resources :factions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_option.rb
class BuyOption < ApplicationRecord
  belongs_to :material
end

app/models/component.rb
class Component < ApplicationRecord
end

app/models/component_in_machine.rb
class ComponentInMachine < ApplicationRecord
  belongs_to :component
  belongs_to :machine
end

app/models/component_material.rb
class ComponentMaterial < ApplicationRecord
  belongs_to :component
  belongs_to :material
end

app/models/faction.rb
class Faction < ApplicationRecord
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/machine_in_section.rb
class MachineInSection < ApplicationRecord
  belongs_to :machine
  belongs_to :section
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :planet
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :planet
  belongs_to :faction
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :faction
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :lastname, :age, :planet_id, :faction_id)
    end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.require(:planet).permit(:name_local, :faction_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_options_helper.rb
module BuyOptionsHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :planet_id %>
    <%= form.text_field :planet_id %>
  </div>

  <div class="field">
    <%= form.label :faction_id %>
    <%= form.text_field :faction_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Age</th>
      <th>Planet</th>
      <th>Faction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.lastname %></td>
        <td><%= person.age %></td>
        <td><%= person.planet_id %></td>
        <td><%= person.faction_id %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Planet:</strong>
  <%= @person.planet_id %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @person.faction_id %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/planets/_form.html.erb
<%= form_with(model: planet, local: true) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_local %>
    <%= form.text_field :name_local %>
  </div>

  <div class="field">
    <%= form.label :faction_id %>
    <%= form.text_field :faction_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>

<table>
  <thead>
    <tr>
      <th>Name local</th>
      <th>Faction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name_local %></td>
        <td><%= planet.faction_id %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name local:</strong>
  <%= @planet.name_local %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @planet.faction_id %>
</p>

<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>