config/routes.rb
Rails.application.routes.draw do
  resources :machine_in_sections
  resources :sections
  resources :machines
  resources :component_in_machines
  resources :component_materials
  resources :components
  resources :buy_options
  resources :materials
  resources :people
  resources :planets
  resources :factions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_option.rb
class BuyOption < ApplicationRecord
  belongs_to :material
end

app/models/component.rb
class Component < ApplicationRecord
end

app/models/component_in_machine.rb
class ComponentInMachine < ApplicationRecord
  belongs_to :component
  belongs_to :machine
end

app/models/component_material.rb
class ComponentMaterial < ApplicationRecord
  belongs_to :component
  belongs_to :material
end

app/models/faction.rb
class Faction < ApplicationRecord
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/machine_in_section.rb
class MachineInSection < ApplicationRecord
  belongs_to :machine
  belongs_to :section
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :planet
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :planet
  belongs_to :faction
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :faction
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/component_materials_controller.rb
class ComponentMaterialsController < ApplicationController
  before_action :set_component_material, only: [:show, :edit, :update, :destroy]

  # GET /component_materials
  # GET /component_materials.json
  def index
    @component_materials = ComponentMaterial.all
  end

  # GET /component_materials/1
  # GET /component_materials/1.json
  def show
  end

  # GET /component_materials/new
  def new
    @component_material = ComponentMaterial.new
  end

  # GET /component_materials/1/edit
  def edit
  end

  # POST /component_materials
  # POST /component_materials.json
  def create
    @component_material = ComponentMaterial.new(component_material_params)

    respond_to do |format|
      if @component_material.save
        format.html { redirect_to @component_material, notice: 'Component material was successfully created.' }
        format.json { render :show, status: :created, location: @component_material }
      else
        format.html { render :new }
        format.json { render json: @component_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /component_materials/1
  # PATCH/PUT /component_materials/1.json
  def update
    respond_to do |format|
      if @component_material.update(component_material_params)
        format.html { redirect_to @component_material, notice: 'Component material was successfully updated.' }
        format.json { render :show, status: :ok, location: @component_material }
      else
        format.html { render :edit }
        format.json { render json: @component_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /component_materials/1
  # DELETE /component_materials/1.json
  def destroy
    @component_material.destroy
    respond_to do |format|
      format.html { redirect_to component_materials_url, notice: 'Component material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component_material
      @component_material = ComponentMaterial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def component_material_params
      params.require(:component_material).permit(:component_id, :material_id, :quantity, :measure_unit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_options_helper.rb
module BuyOptionsHelper
end

app/helpers/component_materials_helper.rb
module ComponentMaterialsHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/component_materials/_form.html.erb
<%= form_with(model: component_material, local: true) do |form| %>
  <% if component_material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(component_material.errors.count, "error") %> prohibited this component_material from being saved:</h2>

      <ul>
        <% component_material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :component_id %>
    <%= form.text_field :component_id %>
  </div>

  <div class="field">
    <%= form.label :material_id %>
    <%= form.text_field :material_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :measure_unit %>
    <%= form.text_field :measure_unit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/component_materials/edit.html.erb
<h1>Editing Component Material</h1>

<%= render 'form', component_material: @component_material %>

<%= link_to 'Show', @component_material %> |
<%= link_to 'Back', component_materials_path %>

app/views/component_materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Component Materials</h1>

<table>
  <thead>
    <tr>
      <th>Component</th>
      <th>Material</th>
      <th>Quantity</th>
      <th>Measure unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @component_materials.each do |component_material| %>
      <tr>
        <td><%= component_material.component_id %></td>
        <td><%= component_material.material_id %></td>
        <td><%= component_material.quantity %></td>
        <td><%= component_material.measure_unit %></td>
        <td><%= link_to 'Show', component_material %></td>
        <td><%= link_to 'Edit', edit_component_material_path(component_material) %></td>
        <td><%= link_to 'Destroy', component_material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Component Material', new_component_material_path %>

app/views/component_materials/new.html.erb
<h1>New Component Material</h1>

<%= render 'form', component_material: @component_material %>

<%= link_to 'Back', component_materials_path %>

app/views/component_materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @component_material.component_id %>
</p>

<p>
  <strong>Material:</strong>
  <%= @component_material.material_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @component_material.quantity %>
</p>

<p>
  <strong>Measure unit:</strong>
  <%= @component_material.measure_unit %>
</p>

<%= link_to 'Edit', edit_component_material_path(@component_material) %> |
<%= link_to 'Back', component_materials_path %>