config/routes.rb
Rails.application.routes.draw do
  resources :machine_in_sections
  resources :sections
  resources :machines
  resources :component_in_machines
  resources :component_materials
  resources :components
  resources :buy_options
  resources :materials
  resources :people
  resources :planets
  resources :factions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy_option.rb
class BuyOption < ApplicationRecord
  belongs_to :material
end

app/models/component.rb
class Component < ApplicationRecord
end

app/models/component_in_machine.rb
class ComponentInMachine < ApplicationRecord
  belongs_to :component
  belongs_to :machine
end

app/models/component_material.rb
class ComponentMaterial < ApplicationRecord
  belongs_to :component
  belongs_to :material
end

app/models/faction.rb
class Faction < ApplicationRecord
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/machine_in_section.rb
class MachineInSection < ApplicationRecord
  belongs_to :machine
  belongs_to :section
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :planet
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :planet
  belongs_to :faction
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :faction
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/machine_in_sections_controller.rb
class MachineInSectionsController < ApplicationController
  before_action :set_machine_in_section, only: [:show, :edit, :update, :destroy]

  # GET /machine_in_sections
  # GET /machine_in_sections.json
  def index
    @machine_in_sections = MachineInSection.all
  end

  # GET /machine_in_sections/1
  # GET /machine_in_sections/1.json
  def show
  end

  # GET /machine_in_sections/new
  def new
    @machine_in_section = MachineInSection.new
  end

  # GET /machine_in_sections/1/edit
  def edit
  end

  # POST /machine_in_sections
  # POST /machine_in_sections.json
  def create
    @machine_in_section = MachineInSection.new(machine_in_section_params)

    respond_to do |format|
      if @machine_in_section.save
        format.html { redirect_to @machine_in_section, notice: 'Machine in section was successfully created.' }
        format.json { render :show, status: :created, location: @machine_in_section }
      else
        format.html { render :new }
        format.json { render json: @machine_in_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_in_sections/1
  # PATCH/PUT /machine_in_sections/1.json
  def update
    respond_to do |format|
      if @machine_in_section.update(machine_in_section_params)
        format.html { redirect_to @machine_in_section, notice: 'Machine in section was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine_in_section }
      else
        format.html { render :edit }
        format.json { render json: @machine_in_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_in_sections/1
  # DELETE /machine_in_sections/1.json
  def destroy
    @machine_in_section.destroy
    respond_to do |format|
      format.html { redirect_to machine_in_sections_url, notice: 'Machine in section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine_in_section
      @machine_in_section = MachineInSection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_in_section_params
      params.require(:machine_in_section).permit(:machine_id, :section_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_options_helper.rb
module BuyOptionsHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/helpers/machine_in_sections_helper.rb
module MachineInSectionsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/machine_in_sections/_form.html.erb
<%= form_with(model: machine_in_section, local: true) do |form| %>
  <% if machine_in_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine_in_section.errors.count, "error") %> prohibited this machine_in_section from being saved:</h2>

      <ul>
        <% machine_in_section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :machine_id %>
    <%= form.text_field :machine_id %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.text_field :section_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machine_in_sections/edit.html.erb
<h1>Editing Machine In Section</h1>

<%= render 'form', machine_in_section: @machine_in_section %>

<%= link_to 'Show', @machine_in_section %> |
<%= link_to 'Back', machine_in_sections_path %>

app/views/machine_in_sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machine In Sections</h1>

<table>
  <thead>
    <tr>
      <th>Machine</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machine_in_sections.each do |machine_in_section| %>
      <tr>
        <td><%= machine_in_section.machine_id %></td>
        <td><%= machine_in_section.section_id %></td>
        <td><%= link_to 'Show', machine_in_section %></td>
        <td><%= link_to 'Edit', edit_machine_in_section_path(machine_in_section) %></td>
        <td><%= link_to 'Destroy', machine_in_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine In Section', new_machine_in_section_path %>

app/views/machine_in_sections/new.html.erb
<h1>New Machine In Section</h1>

<%= render 'form', machine_in_section: @machine_in_section %>

<%= link_to 'Back', machine_in_sections_path %>

app/views/machine_in_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Machine:</strong>
  <%= @machine_in_section.machine_id %>
</p>

<p>
  <strong>Section:</strong>
  <%= @machine_in_section.section_id %>
</p>

<%= link_to 'Edit', edit_machine_in_section_path(@machine_in_section) %> |
<%= link_to 'Back', machine_in_sections_path %>